//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussiaX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RussiaX.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add board.
        /// </summary>
        public static string AddBoard {
            get {
                return ResourceManager.GetString("AddBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must adquire at least one card to participate..
        /// </summary>
        public static string AddBoardInstructions {
            get {
                return ResourceManager.GetString("AddBoardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To participate you must acquire cards.
        /// </summary>
        public static string BoardInstructions {
            get {
                return ResourceManager.GetString("BoardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed..
        /// </summary>
        public static string ChagePasswordConfirm {
            get {
                return ResourceManager.GetString("ChagePasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch image to change it..
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your safety, you must exit and enter the App before changing your password..
        /// </summary>
        public static string ChangePasswordInstructions {
            get {
                return ResourceManager.GetString("ChangePasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have closed your predictions, you can see the predictions of all the users in the menu:.
        /// </summary>
        public static string ClosePredictions {
            get {
                return ResourceManager.GetString("ClosePredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password confirm....
        /// </summary>
        public static string ConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        public static string ConfirmValidation {
            get {
                return ResourceManager.GetString("ConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and the confirm, does not match..
        /// </summary>
        public static string ConfirmValidation2 {
            get {
                return ResourceManager.GetString("ConfirmValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on your internet settings..
        /// </summary>
        public static string ConnectionError1 {
            get {
                return ResourceManager.GetString("ConnectionError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you internet connection..
        /// </summary>
        public static string ConnectionError2 {
            get {
                return ResourceManager.GetString("ConnectionError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, you can write to: jzuluaga55@gmail.com or call the number +57 350 634 2747..
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup Programming.
        /// </summary>
        public static string CupProgramming {
            get {
                return ResourceManager.GetString("CupProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password....
        /// </summary>
        public static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image of his cardboard was received. When the administrator verifies it within 24 hours, he will enable his cardboard to enter the predictions..
        /// </summary>
        public static string DepositConfirmationMessage {
            get {
                return ResourceManager.GetString("DepositConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit prediction.
        /// </summary>
        public static string EditPrediction {
            get {
                return ResourceManager.GetString("EditPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        public static string EmailValidation2 {
            get {
                return ResourceManager.GetString("EmailValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as a guest.
        /// </summary>
        public static string EnterAsAGuest {
            get {
                return ResourceManager.GetString("EnterAsAGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t be changed, please try again..
        /// </summary>
        public static string ErrorChangingPassword {
            get {
                return ResourceManager.GetString("ErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please try again..
        /// </summary>
        public static string ErrorSavingPredictionMessage {
            get {
                return ResourceManager.GetString("ErrorSavingPredictionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name....
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name..
        /// </summary>
        public static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered as a guest, in order to access this option you must register and access the application..
        /// </summary>
        public static string GuestValidation {
            get {
                return ResourceManager.GetString("GuestValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To play &quot;Russia&quot; follow the next instructions:.
        /// </summary>
        public static string Instructions1 {
            get {
                return ResourceManager.GetString("Instructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. In the &quot;Cardboards&quot; menu, purchase one or more cartons..
        /// </summary>
        public static string Instructions2 {
            get {
                return ResourceManager.GetString("Instructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Enter the predictions of each match. You can enter the prediction before starting each game. If you guess the exact result, you will earn 3 points. If you guess the winner or tie with another result you will earn 1 point..
        /// </summary>
        public static string Instructions3 {
            get {
                return ResourceManager.GetString("Instructions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: if for the Colombia - Japan match, you place 2-1, and effectively this result is given, you win 3 points. If Colombia wins by another result, for example: 1-0, 2-0, 3-1, or another, you win 1 point. But if Colombia ties or loses, you do not earn points..
        /// </summary>
        public static string Instructions4 {
            get {
                return ResourceManager.GetString("Instructions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: in the case of games that are defined by penalties, the prediction is made only for the regular game time. I mean before the penalties..
        /// </summary>
        public static string Instructions41 {
            get {
                return ResourceManager.GetString("Instructions41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Win the most points accumulate in the entire tournament. You can check your position in the Classification menu..
        /// </summary>
        public static string Instructions5 {
            get {
                return ResourceManager.GetString("Instructions5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the remote case that two or more users have the same score. The prize will be distributed among all the winners..
        /// </summary>
        public static string Instructions6 {
            get {
                return ResourceManager.GetString("Instructions6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string Invited {
            get {
                return ResourceManager.GetString("Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        public static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LocalGoals {
            get {
                return ResourceManager.GetString("LocalGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter local goals.
        /// </summary>
        public static string LocalGoalsValidation {
            get {
                return ResourceManager.GetString("LocalGoalsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password is incorrect..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is about to close the predictions and you have not yet entered yours..
        /// </summary>
        public static string MatchAboutToFinish {
            get {
                return ResourceManager.GetString("MatchAboutToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My hits.
        /// </summary>
        public static string MyHits {
            get {
                return ResourceManager.GetString("MyHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My prediction.
        /// </summary>
        public static string MyPrediction {
            get {
                return ResourceManager.GetString("MyPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password....
        /// </summary>
        public static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password has been sent, check the new password in your email..
        /// </summary>
        public static string NewPasswordSent {
            get {
                return ResourceManager.GetString("NewPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add an image for the deposit..
        /// </summary>
        public static string NoDepositImageMessage {
            get {
                return ResourceManager.GetString("NoDepositImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no closed predictions. Return to this option when you start the tournament..
        /// </summary>
        public static string NoPredictionsClose {
            get {
                return ResourceManager.GetString("NoPredictionsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option not implemented yet. Comming soon in next version!.
        /// </summary>
        public static string NotImplement {
            get {
                return ResourceManager.GetString("NotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is only available for local users..
        /// </summary>
        public static string NoUserLocalMessage {
            get {
                return ResourceManager.GetString("NoUserLocalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verified.
        /// </summary>
        public static string NoVerified {
            get {
                return ResourceManager.GetString("NoVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password retrieve.
        /// </summary>
        public static string PasswordRetrieve {
            get {
                return ResourceManager.GetString("PasswordRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the registered email, to send a new password..
        /// </summary>
        public static string PasswordRetrieveExplanation {
            get {
                return ResourceManager.GetString("PasswordRetrieveExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 6 characters..
        /// </summary>
        public static string PasswordValidation2 {
            get {
                return ResourceManager.GetString("PasswordValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Matches.
        /// </summary>
        public static string PastMatches {
            get {
                return ResourceManager.GetString("PastMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Matches.
        /// </summary>
        public static string PendingMatches {
            get {
                return ResourceManager.GetString("PendingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone....
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone number..
        /// </summary>
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s over, I&apos;m sorry, you have not earned points.
        /// </summary>
        public static string Points0 {
            get {
                return ResourceManager.GetString("Points0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s finished, congratulations! You have gained 1 point.
        /// </summary>
        public static string Points1 {
            get {
                return ResourceManager.GetString("Points1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s finished, congratulations! you have won 3 points.
        /// </summary>
        public static string Points3 {
            get {
                return ResourceManager.GetString("Points3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have purchased boards and these must be enabled by the administrator..
        /// </summary>
        public static string PredictionInstructions {
            get {
                return ResourceManager.GetString("PredictionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions close matches.
        /// </summary>
        public static string PredictionsCloseMatches {
            get {
                return ResourceManager.GetString("PredictionsCloseMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can&apos;t be created, please try latter..
        /// </summary>
        public static string RegisterUserError {
            get {
                return ResourceManager.GetString("RegisterUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this device.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save prediction.
        /// </summary>
        public static string SavePredictions {
            get {
                return ResourceManager.GetString("SavePredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a board....
        /// </summary>
        public static string SelectBoard {
            get {
                return ResourceManager.GetString("SelectBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a board..
        /// </summary>
        public static string SelectBoardValidation {
            get {
                return ResourceManager.GetString("SelectBoardValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a match....
        /// </summary>
        public static string SelectMatch {
            get {
                return ResourceManager.GetString("SelectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new password.
        /// </summary>
        public static string SendNewPassword {
            get {
                return ResourceManager.GetString("SendNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or login with....
        /// </summary>
        public static string SocialNetworksLogin {
            get {
                return ResourceManager.GetString("SocialNetworksLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something was wrong, please try later..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the image?.
        /// </summary>
        public static string SourceImageQuestion {
            get {
                return ResourceManager.GetString("SourceImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 1.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user exists with the same email..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was create, now you can login with this email and password..
        /// </summary>
        public static string UserRegisteredMessage {
            get {
                return ResourceManager.GetString("UserRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        public static string VisitorGoals {
            get {
                return ResourceManager.GetString("VisitorGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter visitor goals.
        /// </summary>
        public static string VisitorGoalsValidation {
            get {
                return ResourceManager.GetString("VisitorGoalsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current boards:.
        /// </summary>
        public static string YourCurrentBoards {
            get {
                return ResourceManager.GetString("YourCurrentBoards", resourceCulture);
            }
        }
    }
}
